// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    list_id, type_id,title, content, url, thumbnail, category, tags, summary, embedding
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, list_id, type_id, title, content, url, thumbnail, created_at, updated_at, category, tags, summary, embedding
`

type CreateItemParams struct {
	ListID    pgtype.UUID `json:"list_id"`
	TypeID    pgtype.UUID `json:"type_id"`
	Title     pgtype.Text `json:"title"`
	Content   pgtype.Text `json:"content"`
	Url       pgtype.Text `json:"url"`
	Thumbnail pgtype.Text `json:"thumbnail"`
	Category  pgtype.Text `json:"category"`
	Tags      []string    `json:"tags"`
	Summary   pgtype.Text `json:"summary"`
	Embedding []float64   `json:"embedding"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ListID,
		arg.TypeID,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.Thumbnail,
		arg.Category,
		arg.Tags,
		arg.Summary,
		arg.Embedding,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TypeID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Tags,
		&i.Summary,
		&i.Embedding,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items i
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getAllItemsByList = `-- name: GetAllItemsByList :many
SELECT i.id, i.list_id, i.type_id, i.title, i.content, i.url, i.thumbnail, i.created_at, i.updated_at, i.category, i.tags, i.summary, i.embedding
FROM items i
JOIN lists l on i.list_id = l.id
WHERE l.user_id = $1
  AND l.id = $2
`

type GetAllItemsByListParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) GetAllItemsByList(ctx context.Context, arg GetAllItemsByListParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, getAllItemsByList, arg.UserID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.TypeID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.Thumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Category,
			&i.Tags,
			&i.Summary,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one
SELECT id, list_id, type_id, title, content, url, thumbnail, created_at, updated_at, category, tags, summary, embedding
FROM items
WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TypeID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Tags,
		&i.Summary,
		&i.Embedding,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET
    title = COALESCE($2, title),
    content = COALESCE($3, content),
    url = COALESCE($4, url),
    thumbnail = COALESCE($5, thumbnail),
    updated_at = now()
WHERE id = $1
RETURNING id, list_id, type_id, title, content, url, thumbnail, created_at, updated_at, category, tags, summary, embedding
`

type UpdateItemParams struct {
	ID        pgtype.UUID `json:"id"`
	Title     pgtype.Text `json:"title"`
	Content   pgtype.Text `json:"content"`
	Url       pgtype.Text `json:"url"`
	Thumbnail pgtype.Text `json:"thumbnail"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.Thumbnail,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.TypeID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Category,
		&i.Tags,
		&i.Summary,
		&i.Embedding,
	)
	return i, err
}
