// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_metadata.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMetadata = `-- name: AddMetadata :one
INSERT INTO item_metadata (id, item_id, key, value)
VALUES ($1, $2, $3, $4)
RETURNING id, item_id, key, value
`

type AddMetadataParams struct {
	ID     pgtype.UUID `json:"id"`
	ItemID pgtype.UUID `json:"item_id"`
	Key    string      `json:"key"`
	Value  pgtype.Text `json:"value"`
}

func (q *Queries) AddMetadata(ctx context.Context, arg AddMetadataParams) (ItemMetadatum, error) {
	row := q.db.QueryRow(ctx, addMetadata,
		arg.ID,
		arg.ItemID,
		arg.Key,
		arg.Value,
	)
	var i ItemMetadatum
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const deleteMetadataByItem = `-- name: DeleteMetadataByItem :exec
DELETE FROM item_metadata
WHERE item_id = $1
`

func (q *Queries) DeleteMetadataByItem(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMetadataByItem, itemID)
	return err
}

const getItemMetadata = `-- name: GetItemMetadata :many
SELECT id, item_id, key, value
FROM item_metadata
WHERE item_id = $1
`

func (q *Queries) GetItemMetadata(ctx context.Context, itemID pgtype.UUID) ([]ItemMetadatum, error) {
	rows, err := q.db.Query(ctx, getItemMetadata, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemMetadatum
	for rows.Next() {
		var i ItemMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.ItemID,
			&i.Key,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
