// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lists.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, created_at
`

type CreateListParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.ID, arg.UserID, arg.Name)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteList = `-- name: DeleteList :exec
DELETE FROM lists
WHERE id = $1
`

func (q *Queries) DeleteList(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteList, id)
	return err
}

const getList = `-- name: GetList :one
SELECT id, user_id, name, created_at
FROM lists
WHERE id = $1
`

func (q *Queries) GetList(ctx context.Context, id pgtype.UUID) (List, error) {
	row := q.db.QueryRow(ctx, getList, id)
	var i List
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listUserLists = `-- name: ListUserLists :many
SELECT id, user_id, name, created_at
FROM lists
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListUserLists(ctx context.Context, userID pgtype.UUID) ([]List, error) {
	rows, err := q.db.Query(ctx, listUserLists, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []List
	for rows.Next() {
		var i List
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
