// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items (
    id, list_id, user_id, type_id,
    title, content, url, thumbnail
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, list_id, user_id, type_id, title, content, url, thumbnail, created_at, updated_at
`

type CreateItemParams struct {
	ID        pgtype.UUID `json:"id"`
	ListID    pgtype.UUID `json:"list_id"`
	UserID    pgtype.UUID `json:"user_id"`
	TypeID    pgtype.Int4 `json:"type_id"`
	Title     pgtype.Text `json:"title"`
	Content   pgtype.Text `json:"content"`
	Url       pgtype.Text `json:"url"`
	Thumbnail pgtype.Text `json:"thumbnail"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.ID,
		arg.ListID,
		arg.UserID,
		arg.TypeID,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.Thumbnail,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.UserID,
		&i.TypeID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items
WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getItem = `-- name: GetItem :one
SELECT id, list_id, user_id, type_id, title, content, url, thumbnail, created_at, updated_at
FROM items
WHERE id = $1
`

func (q *Queries) GetItem(ctx context.Context, id pgtype.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.UserID,
		&i.TypeID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listItemsByList = `-- name: ListItemsByList :many
SELECT id, list_id, user_id, type_id, title, content, url, thumbnail, created_at, updated_at
FROM items
WHERE list_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListItemsByList(ctx context.Context, listID pgtype.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByList, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.UserID,
			&i.TypeID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.Thumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
SET
    title = COALESCE($2, title),
    content = COALESCE($3, content),
    url = COALESCE($4, url),
    thumbnail = COALESCE($5, thumbnail),
    updated_at = now()
WHERE id = $1
RETURNING id, list_id, user_id, type_id, title, content, url, thumbnail, created_at, updated_at
`

type UpdateItemParams struct {
	ID        pgtype.UUID `json:"id"`
	Title     pgtype.Text `json:"title"`
	Content   pgtype.Text `json:"content"`
	Url       pgtype.Text `json:"url"`
	Thumbnail pgtype.Text `json:"thumbnail"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.Thumbnail,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.UserID,
		&i.TypeID,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Thumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
