// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_types.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createItemType = `-- name: CreateItemType :one
INSERT INTO item_types (name, description)
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateItemTypeParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateItemType(ctx context.Context, arg CreateItemTypeParams) (ItemType, error) {
	row := q.db.QueryRow(ctx, createItemType, arg.Name, arg.Description)
	var i ItemType
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const deleteItemType = `-- name: DeleteItemType :exec
DELETE FROM item_types
WHERE id = $1
`

func (q *Queries) DeleteItemType(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteItemType, id)
	return err
}

const getItemType = `-- name: GetItemType :one
SELECT id, name, description
FROM item_types
WHERE id = $1
`

func (q *Queries) GetItemType(ctx context.Context, id pgtype.UUID) (ItemType, error) {
	row := q.db.QueryRow(ctx, getItemType, id)
	var i ItemType
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const listItemTypes = `-- name: ListItemTypes :many
SELECT id, name, description
FROM item_types
ORDER BY id
`

func (q *Queries) ListItemTypes(ctx context.Context) ([]ItemType, error) {
	rows, err := q.db.Query(ctx, listItemTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemType
	for rows.Next() {
		var i ItemType
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
