// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_tags.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTagToItem = `-- name: AddTagToItem :exec
INSERT INTO item_tags (item_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToItemParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) AddTagToItem(ctx context.Context, arg AddTagToItemParams) error {
	_, err := q.db.Exec(ctx, addTagToItem, arg.ItemID, arg.TagID)
	return err
}

const listItemTags = `-- name: ListItemTags :many
SELECT t.id, t.name
FROM item_tags it
JOIN tags t ON it.tag_id = t.id
WHERE it.item_id = $1
`

func (q *Queries) ListItemTags(ctx context.Context, itemID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listItemTags, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByTag = `-- name: ListItemsByTag :many
SELECT i.id, i.list_id, i.type_id, i.title, i.content, i.url, i.thumbnail, i.created_at, i.updated_at
FROM item_tags it
JOIN items i ON it.item_id = i.id
WHERE it.tag_id = $1
ORDER BY i.created_at DESC
`

func (q *Queries) ListItemsByTag(ctx context.Context, tagID pgtype.UUID) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItemsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.TypeID,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.Thumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromItem = `-- name: RemoveTagFromItem :exec
DELETE FROM item_tags
WHERE item_id = $1 AND tag_id = $2
`

type RemoveTagFromItemParams struct {
	ItemID pgtype.UUID `json:"item_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) RemoveTagFromItem(ctx context.Context, arg RemoveTagFromItemParams) error {
	_, err := q.db.Exec(ctx, removeTagFromItem, arg.ItemID, arg.TagID)
	return err
}
