// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID        pgtype.UUID      `json:"id"`
	ListID    pgtype.UUID      `json:"list_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	TypeID    pgtype.Int4      `json:"type_id"`
	Title     pgtype.Text      `json:"title"`
	Content   pgtype.Text      `json:"content"`
	Url       pgtype.Text      `json:"url"`
	Thumbnail pgtype.Text      `json:"thumbnail"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ItemMetadatum struct {
	ID     pgtype.UUID `json:"id"`
	ItemID pgtype.UUID `json:"item_id"`
	Key    string      `json:"key"`
	Value  pgtype.Text `json:"value"`
}

type ItemTag struct {
	ItemID pgtype.UUID `json:"item_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

type ItemType struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type List struct {
	ID        pgtype.UUID      `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Tag struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type User struct {
	ID        pgtype.UUID      `json:"id"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
